apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamz.fullname" . }}-secrets
  labels:
    {{- include "streamz.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ required "secret.JWT_SECRET is required" .Values.secret.JWT_SECRET | quote }}
  JWT_REFRESH_SECRET: {{ required "secret.JWT_REFRESH_SECRET is required" .Values.secret.JWT_REFRESH_SECRET | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secret.STRIPE_SECRET_KEY | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.secret.STRIPE_WEBHOOK_SECRET | quote }}
  MUX_TOKEN_ID: {{ .Values.secret.MUX_TOKEN_ID | quote }}
  MUX_TOKEN_SECRET: {{ .Values.secret.MUX_TOKEN_SECRET | quote }}
  MUX_WEBHOOK_SECRET: {{ .Values.secret.MUX_WEBHOOK_SECRET | quote }}
  MUX_SIGNING_KEY: {{ .Values.secret.MUX_SIGNING_KEY | quote }}
  MUX_PRIVATE_KEY: {{ .Values.secret.MUX_PRIVATE_KEY | quote }}